CREATE TABLE "project_approvals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"project_id" integer NOT NULL,
	"submitted_by_id" uuid NOT NULL,
	"reviewer_id" uuid,
	"submitted_seconds" integer NOT NULL,
	"approved_seconds" integer,
	"status" text DEFAULT 'pending' NOT NULL,
	"public_message" text,
	"internal_note" text,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "project_approvals" ADD CONSTRAINT "project_approvals_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "project_approvals" ADD CONSTRAINT "project_approvals_submitted_by_id_users_id_fk" FOREIGN KEY ("submitted_by_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "project_approvals" ADD CONSTRAINT "project_approvals_reviewer_id_users_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "project_approvals" ("project_id", "submitted_by_id", "submitted_seconds", "status", "submitted_at")
SELECT p.id, p.user_id, 0, 'pending', p.updated_at
FROM "projects" p
WHERE p.status = 'pending';
--> statement-breakpoint
INSERT INTO "project_approvals" ("project_id", "submitted_by_id", "submitted_seconds", "approved_seconds", "status", "submitted_at", "reviewed_at")
SELECT p.id, p.user_id, COALESCE(p.approved_seconds, 0), COALESCE(p.approved_seconds, 0), 'approved', p.updated_at, p.updated_at
FROM "projects" p
WHERE p.status = 'approved';
--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "status";
--> statement-breakpoint
ALTER TABLE "projects" DROP COLUMN "approved_seconds";
