CREATE TABLE "balance_adjustments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"admin_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"seconds" integer NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
